### ISSUE TITLE
CGaz 5 minimal angle is notably off on low speeds

### ISSUE THREAD

**Issue by suburbski** [etjump/etjump#633] opened 2021-07-23 12:45 UTC
Variable `d_min` seems to be inaccurate, especially between 352 and 400 ups

**Comment by Aciz** [comment] 2021-07-25 08:45
Minimal angle is a bit incorrect term, the correct would be "partial accel zone" or "non-optimal accel zone". It's working as intended, closing.

**Closed by Aciz** 2021-07-25 08:45 UTC
